using System;
using System.Collections.Generic;

namespace EFModel.Models
{
    public partial class Mz
    {
        public Mz()
        {
            Mzdavky = new HashSet<Mzdavky>();
            Mznahr = new HashSet<Mznahr>();
            MzzivPoj = new HashSet<MzzivPoj>();
        }

        public int Id { get; set; }
        public int? UsrOrder { get; set; }
        public bool Sel { get; set; }
        public int? RefZam { get; set; }
        public string Email { get; set; }
        public string RodCisl { get; set; }
        public string OsCislo { get; set; }
        public bool ZvlSazD { get; set; }
        public float? Duvazek { get; set; }
        public double? Tuvazek { get; set; }
        public int? RelDruhM { get; set; }
        public int? RelDruhZ { get; set; }
        public int? RelSkZarucMzda { get; set; }
        public float? Premie { get; set; }
        public decimal? KcOsOhod { get; set; }
        public decimal? KcPremie { get; set; }
        public bool Prohlas { get; set; }
        public int? RefPoj { get; set; }
        public bool PojStat { get; set; }
        public bool BezSoc { get; set; }
        public bool MzdaPoUkonc { get; set; }
        public bool JeSocZam { get; set; }
        public bool JeDuchZam { get; set; }
        public bool JeMrzam { get; set; }
        public bool JeDuch { get; set; }
        public bool JeMr { get; set; }
        public bool JeDohoda10K { get; set; }
        public bool JeSocLpripoj { get; set; }
        public bool JeDuchSporZam { get; set; }
        public bool JeDuchSpor { get; set; }
        public bool BezZdr { get; set; }
        public bool JeZdrZam { get; set; }
        public bool BezDane { get; set; }
        public int? Rok { get; set; }
        public int? RelMes { get; set; }
        public byte? DnyKal { get; set; }
        public byte? DnyStSv { get; set; }
        public byte? DnyPrac { get; set; }
        public float? DovolZ { get; set; }
        public float? Dovol { get; set; }
        public byte? DnySvat { get; set; }
        public float? DnyPlacV { get; set; }
        public float? HodPlacV { get; set; }
        public double? DnyPlacAkceDeti { get; set; }
        public double? HodPlacAkceDeti { get; set; }
        public decimal? KcDov { get; set; }
        public decimal? KcSvatN { get; set; }
        public decimal? KcPlacV { get; set; }
        public decimal? KcPlacAkceDeti { get; set; }
        public float? Neplac { get; set; }
        public float? HodNepl { get; set; }
        public float? Neomluv { get; set; }
        public float? HodNeoml { get; set; }
        public float? Nemoc { get; set; }
        public float? HodNem { get; set; }
        public float? DnyVojCv { get; set; }
        public float? HodVojCv { get; set; }
        public float? DnyVojZs { get; set; }
        public float? DnyMater { get; set; }
        public float? DnyOcr { get; set; }
        public float? DnyOcrdlo { get; set; }
        public float? DnyOpp { get; set; }
        public float? DnyProstoje { get; set; }
        public float? HodMater { get; set; }
        public float? HodOcr { get; set; }
        public float? HodOcrdlo { get; set; }
        public float? HodOpp { get; set; }
        public float? HodProstoje { get; set; }
        public decimal? KcVojCv { get; set; }
        public decimal? KcVojZs { get; set; }
        public decimal? KcZtratV { get; set; }
        public decimal? KcProstoje { get; set; }
        public float? NemKal { get; set; }
        public float? NahrDoby { get; set; }
        public float? NahrDobyDp { get; set; }
        public float? DnyOdpra { get; set; }
        public float? HodOdpra { get; set; }
        public float? HodPracSvat { get; set; }
        public decimal? KcSzM { get; set; }
        public double? PocJedn { get; set; }
        public decimal? KcZaklM { get; set; }
        public decimal? KcPresZm { get; set; }
        public decimal? KcSvatZm { get; set; }
        public float? HodPres { get; set; }
        public decimal? KcPres { get; set; }
        public float? HodSvat { get; set; }
        public float? HodJproc { get; set; }
        public float? HodProst { get; set; }
        public float? HodNoc { get; set; }
        public float? HodJkor { get; set; }
        public float? HodJkor2 { get; set; }
        public float? HodJkor3 { get; set; }
        public decimal? KcSvat { get; set; }
        public decimal? KcJproc { get; set; }
        public decimal? KcProst { get; set; }
        public decimal? KcNoc { get; set; }
        public decimal? KcJkor { get; set; }
        public decimal? KcJkor2 { get; set; }
        public decimal? KcJkor3 { get; set; }
        public decimal? KcOsOhoM { get; set; }
        public decimal? KcPremM { get; set; }
        public decimal? KcDoplat { get; set; }
        public decimal? KcNahrZ { get; set; }
        public string TxNahrZ { get; set; }
        public decimal? KcHrubaM { get; set; }
        public decimal? KcZvZkPj { get; set; }
        public decimal? KcNatPj { get; set; }
        public double? DnyStrav { get; set; }
        public decimal? KcStrav { get; set; }
        public decimal? KcStravNad { get; set; }
        public decimal? KcSocZakLimt { get; set; }
        public decimal? KcSocZak { get; set; }
        public decimal? KcSocZakSniz { get; set; }
        public bool SocUprMvz { get; set; }
        public decimal? KcSocUprEdit { get; set; }
        public decimal? KcSocUprLimt { get; set; }
        public decimal? KcSocUpr { get; set; }
        public decimal? KcSoc { get; set; }
        public decimal? KcSocL { get; set; }
        public decimal? KcSocLsleva { get; set; }
        public decimal? KcSocLslevaSpec { get; set; }
        public decimal? KcZdrZakLimt { get; set; }
        public decimal? KcZdrZak { get; set; }
        public bool ZdrUprMvz { get; set; }
        public decimal? KcZdrUprEdit { get; set; }
        public decimal? KcZdrUprLimt { get; set; }
        public decimal? KcZdrUpr { get; set; }
        public decimal? KcZdr { get; set; }
        public decimal? KcZdrL { get; set; }
        public decimal? KcZdrLshm { get; set; }
        public decimal? KcSocLshm { get; set; }
        public decimal? KcNzdZak { get; set; }
        public decimal? KcNzdDet { get; set; }
        public decimal? KcNzdInv { get; set; }
        public decimal? KcNzdOst { get; set; }
        public decimal? KcZivPoj { get; set; }
        public decimal? KcZivOs { get; set; }
        public decimal? KcOdstup { get; set; }
        public decimal? KcPripoj { get; set; }
        public decimal? KcPripOs { get; set; }
        public decimal? KcZdaM { get; set; }
        public decimal? KcZvZkBp { get; set; }
        public decimal? KcNatBp { get; set; }
        public decimal? KcDanPrS { get; set; }
        public decimal? KcDanZal { get; set; }
        public decimal? KcDanBon { get; set; }
        public decimal? KcZalDan { get; set; }
        public decimal? KcDanUpr { get; set; }
        public decimal? KcPreplDanRz { get; set; }
        public decimal? KcDoplDanBonRz { get; set; }
        public decimal? KcCistaM { get; set; }
        public decimal? KcDavNem { get; set; }
        public decimal? KcNahrNem { get; set; }
        public decimal? KcNadLimitPrijem { get; set; }
        public decimal? KcFiktPovPoj { get; set; }
        public decimal? KcDuchSporZak { get; set; }
        public decimal? KcDuchSporUpr { get; set; }
        public decimal? KcDuchSpor { get; set; }
        public decimal? KcDuchSporSniz { get; set; }
        public float? HodNarokDov { get; set; }
        public float? HodNarokDovSvat { get; set; }
        public float? HodNarokDovCast { get; set; }
        public float? HodDovolZ { get; set; }
        public float? HodDov { get; set; }
        public float? ProplacDovol { get; set; }
        public float? HodProplDov { get; set; }
        public decimal? KcProplacDovol { get; set; }
        public decimal? KcDavOcr { get; set; }
        public decimal? KcDavPpm { get; set; }
        public decimal? KcDavVyr { get; set; }
        public decimal? KcSrazky { get; set; }
        public decimal? KcOsvobP { get; set; }
        public decimal? KcOsvobP2 { get; set; }
        public decimal? KcPrispKarantena { get; set; }
        public decimal? KcNahrN2 { get; set; }
        public decimal? KcNahrN { get; set; }
        public string TxNahrN { get; set; }
        public decimal? KcZaloha { get; set; }
        public decimal? KcCastH { get; set; }
        public decimal? KcVyuct { get; set; }
        public int? RelVyplM { get; set; }
        public decimal? KcCastHm { get; set; }
        public decimal? KcPrum { get; set; }
        public DateTime? Datum { get; set; }
        public DateTime? DatZauct { get; set; }
        public int? RefStr { get; set; }
        public string Zarazeni { get; set; }
        public string Oznacil { get; set; }
        public string Ucetni { get; set; }
        public string Creator { get; set; }
        public string Pozn { get; set; }
        public string Pozn2 { get; set; }
        public DateTime? DatCreate { get; set; }
        public DateTime? DatSave { get; set; }

        public Zam RefZamNavigation { get; set; }
        public ICollection<Mzdavky> Mzdavky { get; set; }
        public ICollection<Mznahr> Mznahr { get; set; }
        public ICollection<MzzivPoj> MzzivPoj { get; set; }
    }
}
